### ISSUE TITLE
如何支持 Graceful Restart

### ISSUE THREAD

**Issue by xuxiangyang** [Allenxuxu/gev#104]
类似于这种逻辑 https://github.com/gobwas/graceful

**Comment by xuxiangyang** [comment]
老进程会等待比如1、2个小时（具体值应该由业务侧决定）如果链接还没有短会直接退出

**Comment by Allenxuxu** [comment]
> 老进程会等待比如1、2个小时（具体值应该由业务侧决定）如果链接还没有短会直接退出

这种策略看起来不是很实用，因为现在大多数容器化了，如果进程一直不退出，会强杀它的，不然可能会影响集群调度

**Comment by xuxiangyang** [comment]
容器化的也是要依赖一个负载均衡吧，这里我有点不是特别熟悉。不过，这类的核心做法应该都是把一个节点从负载均衡中设置不再接受新的请求，等待老请求全部处理完成后进程退出，然后启动新的进程，开始接受新的请求，这样一个过程吧？如果是这样的，问题就是对于节点不是特别多的情况，让一个停止处理新的请求，可能导致其他节点压力过重。更灵活的可能是类似的graceful方案。

类似的需求gin 也可以通过使用 [fvbock/endless](https://github.com/fvbock/endless) 当作middleware来实现的 https://gin-gonic.com/docs/examples/graceful-restart-or-stop/。当然这个是应用层http协议，但因为是重写了传输层的业务，这类插件就没法用了。类似的比如 websocket 或 http等plugins是不是能提供些思路或案例来实现呢？

个人觉得对于websocket或者http这种应用层协议，类似的需求应该是挺普遍的。如果应用层协议可以做的更完善，也应该有助于传输层协议的推广？不过这个可能确实不属于传输层协议的职责

**Comment by Allenxuxu** [comment]
> 容器化的也是要依赖一个负载均衡吧，这里我有点不是特别熟悉。不过，这类的核心做法应该都是把一个节点从负载均衡中设置不再接受新的请求，等待老请求全部处理完成后进程退出，然后启动新的进程，开始接受新的请求，这样一个过程吧？如果是这样的，问题就是对于节点不是特别多的情况，让一个停止处理新的请求，可能导致其他节点压力过重。更灵活的可能是类似的graceful方案。
> 
> 类似的需求gin 也可以通过使用 [fvbock/endless](https://github.com/fvbock/endless) 当作middleware来实现的 [https://gin-gonic.com/docs/examples/graceful-restart-or-stop/。当然这个是应用层http协议，但因为是重写了传输层的业务，这类插件就没法用了。类似的比如](https://gin-gonic.com/docs/examples/graceful-restart-or-stop/%E3%80%82%E5%BD%93%E7%84%B6%E8%BF%99%E4%B8%AA%E6%98%AF%E5%BA%94%E7%94%A8%E5%B1%82http%E5%8D%8F%E8%AE%AE%EF%BC%8C%E4%BD%86%E5%9B%A0%E4%B8%BA%E6%98%AF%E9%87%8D%E5%86%99%E4%BA%86%E4%BC%A0%E8%BE%93%E5%B1%82%E7%9A%84%E4%B8%9A%E5%8A%A1%EF%BC%8C%E8%BF%99%E7%B1%BB%E6%8F%92%E4%BB%B6%E5%B0%B1%E6%B2%A1%E6%B3%95%E7%94%A8%E4%BA%86%E3%80%82%E7%B1%BB%E4%BC%BC%E7%9A%84%E6%AF%94%E5%A6%82) websocket 或 http等plugins是不是能提供些思路或案例来实现呢？
> 
> 个人觉得对于websocket或者http这种应用层协议，类似的需求应该是挺普遍的。如果应用层协议可以做的更完善，也应该有助于传输层协议的推广？不过这个可能确实不属于传输层协议的职责

一般来说，都是新起新的pod/进程，然后杀老的进程。 至于 graceful stop 确实是需要的，一般是停止新的请求，并通知客户端退出（处理完当前请求），库能到做到的也只有这个了，至于能允许老进程处理多久再退出，一般由运维平台觉得把，太慢了，会导致有很多残余进程把，需要强杀他们。

这里我理解需要业务自己来实现这个逻辑？gev 内部提供了  ShutdownWrite 方法

**Comment by xuxiangyang** [comment]
那我先看看怎么能实现吧
