### ISSUE TITLE
EPOLLET or EPOLLLT？

### ISSUE THREAD

**Issue by zhongweikang** [Allenxuxu/gev#106]
大佬好，我全局搜索了代码，没有找到类似 EPOLLET 或者 EPOLLLT 字样的代码，是否就意味着，默认使用的是 EPOLLLT 水平触发？

```go
const readEvent = unix.EPOLLIN | unix.EPOLLPRI
const writeEvent = unix.EPOLLOUT
```

**Comment by Allenxuxu** [comment]
> 大佬好，我全局搜索了代码，没有找到类似 EPOLLET 或者 EPOLLLT 字样的代码，是否就意味着，默认使用的是 EPOLLLT 水平触发？
> 
> ```go
> const readEvent = unix.EPOLLIN | unix.EPOLLPRI
> const writeEvent = unix.EPOLLOUT
> ```

是的

**Comment by zhongweikang** [comment]
使用 EPOLLLT 而不是  EPOLLET 是有什么考量么？

**Comment by Allenxuxu** [comment]
> 使用 EPOLLLT 而不是 EPOLLET 是有什么考量么？

水平触发，代码上处理相对简单，不需要一直读尽，不容易出错，并且 et 未必比 lt 快。

**Comment by zhongweikang** [comment]
好的，感谢解答~
