### ISSUE TITLE
default protocol bug

### ISSUE THREAD

**Issue by yumsai** [Allenxuxu/gev#116]
https://github.com/Allenxuxu/gev/blob/9262fa12b35a46747cf40ee5cd43efa9187adf85/protocol.go#L21
当e切片长度不为0时，已经将数据拷贝进UserBuffer了，但是并没有将buffer *ringbuffer.RingBuffer清空？这是为什么？

**Comment by Allenxuxu** [comment]
这边确实有问题，遗漏了Retrieve(n) , 感谢指出🙏

**Comment by woshihuo12** [comment]
。。。。刚想过来问这个问题，居然发现恰好有人提了。。

**Comment by woshihuo12** [comment]
这里还想请问另外一个问题：
`	copy(userBuffer, s)
		copy(userBuffer[len(s):], e)

		return nil, userBuffer`

将数据拷贝到userBuffer里面， 那外面在使用的时候，是如何知道userBuffer的有效长度的呢？

**Comment by woshihuo12** [comment]
https://github.com/Allenxuxu/gev/blob/9262fa12b35a46747cf40ee5cd43efa9187adf85/protocol.go#L32

还想问下，这个拷贝到userBuffer的数据，外面使用的时候，是如何知道其有效长度的呢？

**Comment by Allenxuxu** [comment]
> https://github.com/Allenxuxu/gev/blob/9262fa12b35a46747cf40ee5cd43efa9187adf85/protocol.go#L32
> 
> 还想问下，这个拷贝到userBuffer的数据，外面使用的时候，是如何知道其有效长度的呢？

这里也有问题，应该userBuffer[:size]， 我一起修复了 https://github.com/Allenxuxu/gev/pull/123。
非常感谢两位🙏。
