### ISSUE TITLE
这里为什么是一个循环啊？？？

### ISSUE THREAD

**Issue by yumsai** [Allenxuxu/gev#117]
https://github.com/Allenxuxu/gev/blob/9262fa12b35a46747cf40ee5cd43efa9187adf85/connection.go#L208

**Comment by Allenxuxu** [comment]
尽可能的把内存中所有数据处理完

**Comment by yumsai** [comment]
可是我看了与之相关的代码，`c.protocol.UnPacket(c, buffer)`中的buffer要么是`c.buffer`,要么是`c.inBuffer`，只有handleRead调用了handleProtocol，handleRead的过程中，没有其他协程使用`c.buffer`和`c.inBuffer`，所以说只需要一次`c.protocol.UnPacket(c, buffer)`，无须循环呀！我还是不太明白
