### ISSUE TITLE
事件处理顺序如何排序，这里的排序有什么讲究？

### ISSUE THREAD

**Issue by yumsai** [Allenxuxu/gev#119]
@xuxiangyang 
var rEvents Event
				if ((events[i].Events & unix.POLLHUP) != 0) && ((events[i].Events & unix.POLLIN) == 0) {
					rEvents |= EventErr
				}
				if (events[i].Events&unix.EPOLLERR != 0) || (events[i].Events&unix.EPOLLOUT != 0) {
					rEvents |= EventWrite
				}
				if events[i].Events&(unix.EPOLLIN|unix.EPOLLPRI|unix.EPOLLRDHUP) != 0 {
					rEvents |= EventRead
				} @ @xuxiangyang

**Comment by xuxiangyang** [comment]
这个我当时调研了下，没特别看懂，主要是ws实现上有点理解困难。。。参考了 https://github.com/eranyanay/1m-go-websockets，然后epoll 选择了 https://github.com/mailru/easygo/tree/master/netpoll。如果你是和我一样对ws选型，这个方案也可以看看。

如果只是sdk使用问题，直接问作者会好点

**Comment by yumsai** [comment]
websocket是应用层自己实现了，我问的问题是为什么epoll_wait处理事件顺序是这样的

**Comment by Allenxuxu** [comment]
就是先处理 err，再处理读写标志位的常规顺序啊

**Comment by yumsai** [comment]
谢谢
