### ISSUE TITLE
Are the writes to socket blocking or non-blocking?

### ISSUE THREAD

**Issue by indexk09** [Allenxuxu/gev#120]
The write to socket here in the websocket broadcast example https://github.com/Allenxuxu/gev/blob/master/example/websocket/main.go#L144 makes a blocking or non blocking system call? If blocking is there anyway to do or advisable to do non-blocking system call for low latency applications?

**Comment by Allenxuxu** [comment]
It's non blocking call.

**Comment by indexk09** [comment]
@Allenxuxu Can you please share some info on how this would make non blocking "system call". Also if is non-blocking system call how do I make sure I don't run into OOM? for example, lets says server is constantly broadcasting/writing at a high speed and clients may not keep up with that speed. wouldn't that result in OOM? if so, how do I prevent it?

**Comment by Allenxuxu** [comment]
> @Allenxuxu Can you please share some info on how this would make non blocking "system call". Also if is non-blocking system call how do I make sure I don't run into OOM? for example, lets says server is constantly broadcasting/writing at a high speed and clients may not keep up with that speed. wouldn't that result in OOM? if so, how do I prevent it?

https://github.com/Allenxuxu/gev/issues/52

look at this
