### ISSUE TITLE
这里的循环是不是换成if也行

### ISSUE THREAD

**Issue by yumsai** [Allenxuxu/gev#121]
https://github.com/Allenxuxu/gev/blob/9262fa12b35a46747cf40ee5cd43efa9187adf85/connection.go#L208
c.protocol.UnPacket(c, buffer)中的buffer要么是c.buffer,要么是c.inBuffer，只有handleRead调用了handleProtocol，handleRead的过程中，没有其他协程使用c.buffer和c.inBuffer，所以说只需要一次c.protocol.UnPacket(c, buffer)，无须循环呀！我还是不太明白

**Comment by Allenxuxu** [comment]
是的，但是我我想将读到的数据解析出来

**Comment by yumsai** [comment]
恩恩，晓得了
