### ISSUE TITLE
对于gev的一些疑问

### ISSUE THREAD

**Issue by cexll** [Allenxuxu/gev#127]
运行gev为什么需要先运行一个http服务呢? 
```go
func main() {
	go func() {
		if err := http.ListenAndServe(":6060", nil); err != nil {
			panic(err)
		}
	}()
}
```
启动gev之后1883端口为什么无法连接
![image](https://user-images.githubusercontent.com/26520956/182549359-f6dd8165-d919-40a3-9f87-b7302286b501.png)

![image](https://user-images.githubusercontent.com/26520956/182549199-97dcd664-e26d-4628-948b-e9e83e4b7bdf.png)

希望大佬解答

**Comment by Allenxuxu** [comment]
`  _ "net/http/pprof"`

开 pprof
