### ISSUE TITLE
OnConnect 里使用 c.set 的请教!

### ISSUE THREAD

**Issue by maxbad** [Allenxuxu/gev#137]
在 OnConnect 里面用c.set设置的数据,在OnClose的时候需要自己清理吗? 还是连接断开的时候会自动释放啊呢?

**Comment by Allenxuxu** [comment]
> 在 OnConnect 里面用c.set设置的数据,在OnClose的时候需要自己清理吗? 还是连接断开的时候会自动释放啊呢?

Go 是有 GC 的语言，只要你别再外面其他地方持有就行。
