### ISSUE TITLE
比较关心QPS而非吞吐能力

### ISSUE THREAD

**Issue by lazy-luo** [Allenxuxu/gev#16]
有关更具实用性的测试，参见：
https://blog.csdn.net/ws_lzy007/article/details/102664570
希望有类似的对比测试数据。

**Comment by Allenxuxu** [comment]
目前 gev 没有计划支持 http 协议，仅仅定位做个简洁的 TCP 库（通过新增插件是可以的，类似库中的 websocket）。所以，你文章里的基于 HTTP 的 QPS 测试可能做不了。

目前，库中 PingPong 测试的客户端是每次发送固定长度的包，所以简单除一下也就是基于 PingPong 协议的 QPS 了。
https://github.com/Allenxuxu/gev/blob/master/benchmarks/client/main.go

**Comment by MrChang0** [comment]
@lazy-luo  这种命题就有问题，如果是测试实用性性能，那就是要融入业务，看看每个网络库能给业务带来多少实质性得提升。然而给的例子中仅仅测试http得响应，看不出来和pingpong测试有什么本质区别。

**Comment by lazy-luo** [comment]
@MrChang0 意义在于ping-pong测试少数连接就可以跑满带宽，况且是直接转发，没有完整性校验及沾包处理；不要小看http相应，req/rsp才真正体现QPS，而QPS高低在特定带宽及硬件环境下与调度性能强相关

**Comment by MrChang0** [comment]
@lazy-luo 有一点在于gev定义为网络库，而非“框架”。网络库关心事情更偏底层，上层可以进行自由得进行协议封装。协议层不同的实现不同的处理也可能有很大的性能差异。如果你有比较好的实现(http)，可以基于gev做一版，看看性能如何。
