### ISSUE TITLE
gev在代理的场景如何应用？

### ISSUE THREAD

**Issue by rocqina** [Allenxuxu/gev#17]
onConnect的连接是客户端连接，每个客户端连接成功注册为一个downSession，同时希望他进行一系列逻辑处理以后，在每一个downSession里创建一个上行的连接，作为代理转发。这个
C++的libevent库可以很容易处理这种场景，刚接触gev，不是很清楚，如何处理这种场景

**Comment by rocqina** [comment]
我现在的实现逻辑是原生库，监听到的连接，创建一个downSession，同时起一个goroutine保持长连接，同时在这个downSession里创建一个客户端，分别再起两个goroutine对clientConn和serverConn进行简单的流复制

**Comment by Allenxuxu** [comment]
使用 gev 监听到的连接无需单独启 goroutine 来保持长链接。
可以在将 downSession  通过Connection.SetContext  存储。
在这个 downSession 里创建一个客户端，在 OnMessage 回调函数里进行 流复制，如果害怕 流复制 过于耗时，可以单独起 goroutine 来做。

**Comment by rocqina** [comment]
OnMessage我理解是下行客户端发送过来才触发的，如果上行server主动发送给downSession的客户端，怎么触发响应呢

**Comment by Allenxuxu** [comment]
使用 `Connection.Send` ，这个方法，可以主动推送数据，可以看看这个例子：https://github.com/Allenxuxu/gev/blob/master/example/pushmessage/main.go

**Comment by rocqina** [comment]
你这个例子中type Server struct ，在我的应用中相当于是一个代理，conn   *list.List相当于下行连接，我可以创建session并且在c的context中存session，我需要在session中创建一个客户端，去连接一个上行的server，消息在上行serer和下行的客户端通过代理proxy转发，我的意思是如果上行的server主动发送信息给客户端，代理这部分怎么响应。我现在是通过传统的流复制来做的，我觉得跟epoll的触发响应效率要差。gev我觉得对下行客户端的处理很好，但是我不清楚上行server怎么能通过epoll触发。在C++的libevent库里，上下行的读写响应都可以在一个event_base_loop中触发。我的上下行流复制实现大概是下面这样的，我是想gev的架构怎么实行，最好是不用流复制
// 从服务器到客户端
go func() {
		if session.serverReader != nil {
		bufLen := session.serverReader.Buffered()
		// 将bufio中的剩余内容写入对端
		if bufLen > 0 {
			buf := make([]byte, bufLen)
			session.serverReader.Read(buf)
			session.clientConn.Write(buf)
		}
		// 释放bufio
		session.serverReader = nil
	}
	// 简单的流复制
	buffer := make([]byte, bufioReaderBufSize)
	_, err := IOCopyBuffer(session.clientConn, session.serverConn, buffer)
	// 流复制结束，说明其中一方关闭了连接
	if (err == ErrReadFailed) {
		// 服务器关闭了连接，尝试重连
		session.tryReconnect(currentReconnectCounter)
	} else {
		// 客户端关闭了连接，结束会话
		session.quitCh <- true
	}
}()

// 从客户端到服务器
go func() {
		if session.clientReader != nil {
		bufLen := session.clientReader.Buffered()
		// 将bufio中的剩余内容写入对端
		if bufLen > 0 {
			buf := make([]byte, bufLen)
			session.clientReader.Read(buf)
			session.serverConn.Write(buf)
		}
		// 释放bufio
		session.clientReader = nil
	}
	// 简单的流复制
	buffer := make([]byte, bufioReaderBufSize)
	bufferLen, err := IOCopyBuffer(session.serverConn, session.clientConn, buffer)
	// 流复制结束，说明其中一方关闭了连接
	if (err == ErrWriteFailed || err == ErrWriteMissFailed)  {
		// 服务器关闭了连接，尝试重连
		session.tryReconnect()
		// 若重连成功，尝试将缓存中的内容转发到新服务器
		// getStat() 会锁定到重连成功或放弃重连为止
		if bufferLen > 0 && err == ErrWriteFailed && session.getStat() == StatRunning {
			session.serverConn.Write(buffer[0:bufferLen])
		}
	} else {
		// 客户端关闭了连接，结束会话
		session.quitCh <- true
	}
}()

**Comment by Allenxuxu** [comment]
把代码 用 markdown code 格式，这样看，太难了。

**Comment by Allenxuxu** [comment]
> 你这个例子中type Server struct ，在我的应用中相当于是一个代理，conn *list.List相当于下行连接，我可以创建session并且在c的context中存session，我需要在session中创建一个客户端，去连接一个上行的server，消息在上行serer和下行的客户端通过代理proxy转发，我的意思是如果上行的server主动发送信息给客户端，代理这部分怎么响应。我现在是通过传统的流复制来做的，我觉得跟epoll的触发响应效率要差。gev我觉得对下行客户端的处理很好，但是我不清楚上行server怎么能通过epoll触发。在C++的libevent库里，上下行的读写响应都可以在一个event_base_loop中触发。我的上下行流复制实现大概是下面这样的，我是想gev的架构怎么实行，最好是不用流复制

从 ringbuffer 中读取所有的数据，然后通过 Connection.Send 这个方法来发送啊

**Comment by rocqina** [comment]
代码不贴了，也不是很重要，就是之前实现的是goroutine-per-connection，gev如果支持代理的话，最好能提供一个代理的例子，现在OnMessage，OnConnect，OnClose都是针对下行客户端链接过来响应的。怎么有上行服务器发送过来的响应

**Comment by rocqina** [comment]
> > 你这个例子中type Server struct ，在我的应用中相当于是一个代理，conn *list.List相当于下行连接，我可以创建session并且在c的context中存session，我需要在session中创建一个客户端，去连接一个上行的server，消息在上行serer和下行的客户端通过代理proxy转发，我的意思是如果上行的server主动发送信息给客户端，代理这部分怎么响应。我现在是通过传统的流复制来做的，我觉得跟epoll的触发响应效率要差。gev我觉得对下行客户端的处理很好，但是我不清楚上行server怎么能通过epoll触发。在C++的libevent库里，上下行的读写响应都可以在一个event_base_loop中触发。我的上下行流复制实现大概是下面这样的，我是想gev的架构怎么实行，最好是不用流复制
> 
> 从 ringbuffer 中读取所有的数据，然后通过 Connection.Send 这个方法来发送啊

我问的不是发送的问题，我问的是作为上行服务器的客户端，读写触发响应的问题

**Comment by Allenxuxu** [comment]
我明白你的意思了，其实你是需要一个客户端库（去连接别的 server）融入 gev 。
目前 gev 并没有支持 client，你想使用的话需要 启一个 goroutine 来维持这个客户端。

**Comment by rocqina** [comment]
好的
