### ISSUE TITLE
[Gev] Server start (:1833) 请问这个信息可以关闭吗？

### ISSUE THREAD

**Issue by defsky** [Allenxuxu/gev#19]
服务器启动的时候会显示 [Gev] Server start (:1833) ，请问可以关闭或者自定义吗？

**Comment by Allenxuxu** [comment]
> 服务器启动的时候会显示 [Gev] Server start (:1833) ，请问可以关闭或者自定义吗？

我最近刚加的 😅，内置打印这个信息确实不太好，我来把这个去掉把。

**Comment by defsky** [comment]
喔 好的，怎么不弄个OnStart 的回调接口呢？

> > 服务器启动的时候会显示 [Gev] Server start (:1833) ，请问可以关闭或者自定义吗？
> 
> 我最近刚加的 ，内置打印这个信息确实不太好，我来把这个去掉把。

**Comment by Allenxuxu** [comment]
> 喔 好的，怎么不弄个OnStart 的回调接口呢？
> 
> > > 服务器启动的时候会显示 [Gev] Server start (:1833) ，请问可以关闭或者自定义吗？
> > 
> > 
> > 我最近刚加的 ，内置打印这个信息确实不太好，我来把这个去掉把。

我害怕回调太多，反而不好。你觉得你需要 OnStart 这个回调吗？

**Comment by defsky** [comment]
> > 喔 好的，怎么不弄个OnStart 的回调接口呢？
> > > > 服务器启动的时候会显示 [Gev] Server start (:1833) ，请问可以关闭或者自定义吗？
> > > 
> > > 
> > > 我最近刚加的 ，内置打印这个信息确实不太好，我来把这个去掉把。
> 
> 我害怕回调太多，反而不好。你觉得你需要 OnStart 这个回调吗？

我也说不好，只是之前用evio的时候好像有OnStart这个接口， 可以做一些服务器启动前的准备工作吧，不过不用这个回调也能做。。。可能只是有点强迫症吧。。

**Comment by Allenxuxu** [comment]
> > > 喔 好的，怎么不弄个OnStart 的回调接口呢？
> > > > > 服务器启动的时候会显示 [Gev] Server start (:1833) ，请问可以关闭或者自定义吗？
> > > > 
> > > > 
> > > > 我最近刚加的 ，内置打印这个信息确实不太好，我来把这个去掉把。
> > 
> > 
> > 我害怕回调太多，反而不好。你觉得你需要 OnStart 这个回调吗？
> 
> 我也说不好，只是之前用evio的时候好像有OnStart这个接口， 可以做一些服务器启动前的准备工作吧，不过不用这个回调也能做。。。可能只是有点强迫症吧。。

那就暂时先不加把。
