### ISSUE TITLE
目前有哪些项目或厂商使用gev嘛？另外除了性能测试数据之外，相比gnet还有哪些优势？

### ISSUE THREAD

**Issue by KaiwenWang** [Allenxuxu/gev#20]

**Comment by Allenxuxu** [comment]
@KaiwenWang 
目前应该是还没有知名项目使用的，毕竟才开源两个多月😅。

相比 gnet，除去性能对比，我觉得 gev 是将自己定位成一个精简网络库，提供的是底层安全可靠的tcp服务，舍弃了其他很多非必需的东西，尽可能保持简洁，代码也非常精简，让开发者易于完全掌控。
对于更上层的协议支持， gev 提供插件化的思路，让开发者可以基于 gev 快速构建自己的服务。
