### ISSUE TITLE
Websocket如何實踐廣播跟多播？

### ISSUE THREAD

**Issue by thaiwu0107** [Allenxuxu/gev#21]
Websocket 要怎麼廣播跟多播給客戶端呢？
要自己存一個 map 來使用嗎？

或是底層已經有一個 map 可以開放出來避免重複儲存？

**Comment by Allenxuxu** [comment]
建议是自己存一个 map 来使用， 如果开放底层的map会必然导致一些竞争问题，比起节约的这一点内存，实在得不偿失。
