### ISSUE TITLE
客户端连接后立即关闭，onConnect 回调函数晚于 onClose 执行

### ISSUE THREAD

**Issue by defsky** [Allenxuxu/gev#24]
连接关闭时获取到连接的Context为nil导致panic， 看起来是不是框架里面有毛病？明明建立连接的时候设置了context的

![panic](https://user-images.githubusercontent.com/15100900/70709198-4ce8cd00-1d17-11ea-96d3-45cad9a1ae81.png)
![onconnect](https://user-images.githubusercontent.com/15100900/70709205-540fdb00-1d17-11ea-8806-995ccab412c1.png)
![onclose](https://user-images.githubusercontent.com/15100900/70709216-5a05bc00-1d17-11ea-812d-57fda885385e.png)

**Comment by Allenxuxu** [comment]
![image](https://user-images.githubusercontent.com/20566897/70710703-be764a80-1d1a-11ea-8a41-82039e921bec.png)

应该不会有问题， 你多 debug 一下。

如果还有问题，发下完整源码，我运行看看。

类型断言 最好采用这种方式：
```go
value, ok := a.(string)
```

**Comment by defsky** [comment]
这种类型的连接和断开也运行了至少上百次了 ，也才遇到这一次panic，从这个业务代码上看起来明明是设置了context的，怎么取出来就是空的呢

**Comment by Allenxuxu** [comment]
https://github.com/Allenxuxu/gev/blob/a71b54704fec3e8fac400d2a2bfbeda7a6bd4a8d/server.go#L102

我大概猜测到原因，执行 onConnect 时机的问题，onConnect 是在加入 epoll 之后执行，并且不是在 IO 线程执行。
可能是 刚好加入 epoll 后，在 onConnect 回调之前，客户端断开了链接，IO 线程就直接调用了 onClose 回调。

**Comment by Allenxuxu** [comment]
9d9d1c0251eb35666afb0b2839b1ac2ae0f138b6

fix

**Comment by defsky** [comment]
好的 3q  那我继续玩

**Comment by Allenxuxu** [comment]
> 好的 3q 那我继续玩

😄好的，感谢报 bug

**Comment by defsky** [comment]
> > 好的 3q 那我继续玩
> 
> 好的，感谢报 bug

怎么更新不了呢？ 是不是需要你这边怎么发布一下？

**Comment by Allenxuxu** [comment]
> > > 好的 3q 那我继续玩
> > 
> > 
> > 好的，感谢报 bug
> 
> 怎么更新不了呢？ 是不是需要你这边怎么发布一下？

发布了
https://github.com/Allenxuxu/gev/releases/tag/v0.1.5

**Comment by Allenxuxu** [comment]
https://github.com/Allenxuxu/gev/releases/tag/v0.1.8

**Comment by defsky** [comment]
> 老哥，拉这个最新的试下：
> https://github.com/Allenxuxu/gev/releases/tag/v0.1.8

好像没啥问题了

**Comment by Allenxuxu** [comment]
> > 老哥，拉这个最新的试下：
> > https://github.com/Allenxuxu/gev/releases/tag/v0.1.8
> 
> 好像没啥问题了

😄好。
感谢老哥帮忙测试！
