### ISSUE TITLE
下载报错呀

### ISSUE THREAD

**Issue by xiaoqinguo** [Allenxuxu/gev#26]
D:\>go get -u github.com/Allenxuxu/gev
\# github.com/Allenxuxu/gev/eventloop
Golang\src\github.com\Allenxuxu\gev\eventloop\eventloop.go:19:11: undefined: poller.Poller
\# github.com/Allenxuxu/gev/listener
Golang\src\github.com\Allenxuxu\gev\listener\listener.go:15:38: undefined: unix.Sockaddr
Golang\src\github.com\Allenxuxu\gev\listener\listener.go:47:11: undefined: unix.SetNonblock
Golang\src\github.com\Allenxuxu\gev\listener\listener.go:60:19: undefined: unix.Accept
Golang\src\github.com\Allenxuxu\gev\listener\listener.go:62:14: undefined: unix.EAGAIN
Golang\src\github.com\Allenxuxu\gev\listener\listener.go:67:13: undefined: unix.SetNonblock
Golang\src\github.com\Allenxuxu\gev\listener\listener.go:68:8: undefined: unix.Close

**Comment by xiaoqinguo** [comment]
D:\>go get -u github.com/Allenxuxu/gev
\# github.com/Allenxuxu/gev/eventloop
Golang\src\github.com\Allenxuxu\gev\eventloop\eventloop.go:19:11: undefined: poller.Poller
\# github.com/Allenxuxu/gev/listener
Golang\src\github.com\Allenxuxu\gev\listener\listener.go:15:38: undefined: unix.Sockaddr
Golang\src\github.com\Allenxuxu\gev\listener\listener.go:47:11: undefined: unix.SetNonblock
Golang\src\github.com\Allenxuxu\gev\listener\listener.go:60:19: undefined: unix.Accept
Golang\src\github.com\Allenxuxu\gev\listener\listener.go:62:14: undefined: unix.EAGAIN
Golang\src\github.com\Allenxuxu\gev\listener\listener.go:67:13: undefined: unix.SetNonblock
Golang\src\github.com\Allenxuxu\gev\listener\listener.go:68:8: undefined: unix.Close

**Comment by xiaoqinguo** [comment]
git clone https://github.com/golang/sys.git %GOPATH%/src/golang.org/x/sys

**Comment by Allenxuxu** [comment]
> D:>go get -u github.com/Allenxuxu/gev
> # github.com/Allenxuxu/gev/eventloop
> Golang\src\github.com\Allenxuxu\gev\eventloop\eventloop.go:19:11: undefined: poller.Poller
> # github.com/Allenxuxu/gev/listener
> Golang\src\github.com\Allenxuxu\gev\listener\listener.go:15:38: undefined: unix.Sockaddr
> Golang\src\github.com\Allenxuxu\gev\listener\listener.go:47:11: undefined: unix.SetNonblock
> Golang\src\github.com\Allenxuxu\gev\listener\listener.go:60:19: undefined: unix.Accept
> Golang\src\github.com\Allenxuxu\gev\listener\listener.go:62:14: undefined: unix.EAGAIN
> Golang\src\github.com\Allenxuxu\gev\listener\listener.go:67:13: undefined: unix.SetNonblock
> Golang\src\github.com\Allenxuxu\gev\listener\listener.go:68:8: undefined: unix.Close

目前尚不支持 Windows 。



> git clone https://github.com/golang/sys.git %GOPATH%/src/golang.org/x/sys
> 依赖包要自己下载
> 
> 但还是报上面的错，没有人遇到吗？

golang.org 下载不下来，可以用梯子，或者使用 go mod 设置 GOPROXY

**Comment by xiaoqinguo** [comment]
虽然运行环境都是linux，但开发调试都是window呀，近期考虑支持吗？

**Comment by Allenxuxu** [comment]
肯定会支持的，但是最近太忙了，还没能安排上

**Comment by Allenxuxu** [comment]
#7

**Comment by Allenxuxu** [comment]
https://github.com/Allenxuxu/gev/issues/7
