### ISSUE TITLE
Connection.ShutdownWrite()

### ISSUE THREAD

**Issue by hagbei** [Allenxuxu/gev#27]
调用了Connection.ShutdownWrite()怎么不能断开链接，调用后客户端依然可以发送数据，服务端也能收到数据。

**Comment by Allenxuxu** [comment]
> 调用了Connection.ShutdownWrite()怎么不能断开链接，调用后客户端依然可以发送数据，服务端也能收到数据。

ShutdownWrite 仅仅是关闭写端。 服务端 ShutdownWrite 之后，客户端会 read 0，此时客户端应该关闭连接。
