### ISSUE TITLE
建议 gev 加入 techempower 的性能对比测试

### ISSUE THREAD

**Issue by sbilly** [Allenxuxu/gev#37]
建议 gev 加入 techempower 的性能对比测试

相关测试的介绍地址：https://www.techempower.com/benchmarks/

**Comment by Allenxuxu** [comment]
第一次知道这个，感谢告知😄。

**Comment by kiyonlin** [comment]
> 第一次知道这个，感谢告知😄。
> 
> 等我有时间，会安排上的。我不太了解这个 techempower ，如果你愿意的话，可以直接PR。

建议查看一下[general-test-requirements](https://github.com/TechEmpower/FrameworkBenchmarks/wiki/Project-Information-Framework-Tests-Overview#general-test-requirements)，第一条要求就是**生产级别的实现**。

假如只是做个简单的请求头解析，参加`plaintext`的测试（比如`gnet`，@panjf2000 你怎么看？），我感觉没有意义，对其他框架来说，有点“作弊”的味道。

要是正儿八紧地完整实现`http`协议，我还是很支持的。

**Comment by lesismal** [comment]
非完整功能的异步网络库做这个测试没有意义
gnet已经加入了，但是只能忽悠外行。功能不完整的代码，跟人家http功能完整的框架去比性能，除了网络部分，http的部分相当于只做了别人的十分之一甚至百人之一，然后说比别人性能强，这非常不严谨、完全是自欺欺人的
除非异步网络库也加入了相对完整的功能，再去对比才有意义

异步库的优势在于极大减少高并发场景下的协程数量，并降低与其相对应的协程内存、协程调度等成本，要对比可以只对比4层数据传输的性能。gev/gnet就网络部分而言，应该对标标准库的net而不是net/http
