### ISSUE TITLE
server的主loop相关问题

### ISSUE THREAD

**Issue by M6ZeroG** [Allenxuxu/gev#40]
注意到Listener被单独放置在server.loop里形成一个只包含一个fd的event-loop，这样比起将Listener放置在单独协程里阻塞的Accept并派发TCP连接到各个子event-loop里的方式有什么优势，仅仅是为了保证纯异步非阻塞吗:laughing:，请教。

**Comment by Allenxuxu** [comment]
在 go 里，似乎两种方式差别不大。具体有没有优势可能需要对比测试下，这和golang底层的协程调度有关。
