### ISSUE TITLE
cannot use int(time.Now().Unix()) (type int) as type int64 in argument to conn.activeTime.Swap

### ISSUE THREAD

**Issue by goudai** [Allenxuxu/gev#41]
go version : 1.15

![image](https://user-images.githubusercontent.com/16605628/92581691-9116f700-f2c2-11ea-9e32-f2dd84a4cf41.png)

**Comment by Allenxuxu** [comment]
感谢指出，已经修复了。

重新执行 `go get -u github.com/Allenxuxu/gev` 试试吧😄

**Comment by goudai** [comment]
依然如此。

**Comment by goudai** [comment]
![image](https://user-images.githubusercontent.com/16605628/92683470-895c5e80-f365-11ea-929b-6684ac373b3e.png)

**Comment by goudai** [comment]
![image](https://user-images.githubusercontent.com/16605628/92683611-ec4df580-f365-11ea-8624-2e5fbe73a262.png)
使用master ok

**Comment by Allenxuxu** [comment]
老哥，还有问题吗？
没有我就关issue了啊。
