### ISSUE TITLE
error

### ISSUE THREAD

**Issue by xxxlzj520** [Allenxuxu/gev#43]
mac SDK1.4和1.5都试过。

../../pkg/mod/github.com/!allenxuxu/gev@v0.1.9/connection/connection.go:65:31: cannot use int(time.Now().Unix()) (type int) as type int64 in argument to conn.activeTime.Swap
../../pkg/mod/github.com/!allenxuxu/gev@v0.1.9/connection/connection.go:137:28: cannot use int(time.Now().Unix()) (type int) as type int64 in argument to c.activeTime.Swap

**Comment by Allenxuxu** [comment]
拉最新的代码，这个问题已经修复过了
