### ISSUE TITLE
Possible to do a reverse proxy example?

### ISSUE THREAD

**Issue by gitmko0** [Allenxuxu/gev#47]
great software,

Possible to do a reverse proxy example?

**Comment by gitmko0** [comment]
can be faster than 
https://github.com/panjf2000/gnet
just curious

**Comment by Allenxuxu** [comment]
> great software,
> 
> Possible to do a reverse proxy example?

I don't have time recently. You can try to do it.

**Comment by Allenxuxu** [comment]
> possible to make it faster than this?
> https://github.com/panjf2000/gnet ?
> just curious

We have a similar implementation, I think the performance is close, but gev is simpler and purer. You can test it yourself.
