### ISSUE TITLE
feature: server option加入connection ringbuffer maxSize限制？ 

### ISSUE THREAD

**Issue by rfyiamcool** [Allenxuxu/gev#52]
有些弱网客户端消费太慢，导致推送端send()的数据一直堆积在socket缓冲区和ringbuffer缓冲区。

**Comment by Allenxuxu** [comment]
这个功能我觉得是需要的，我会尽快 commit。如果你感兴趣，也可以提 PR 。

**Comment by Allenxuxu** [comment]
https://github.com/Allenxuxu/gev/pull/54

**Comment by Allenxuxu** [comment]
> #54

提供了，获取当前 connection ringbuffer length 的接口，可以感知到ringbuffer 缓冲区的堆积，然后业务来处理降级。

**Comment by rfyiamcool** [comment]
感谢
