### ISSUE TITLE
gnet 和 gev 的压测结果不一致问题

### ISSUE THREAD

**Issue by yale8848** [Allenxuxu/gev#6]
gev，[gnet](https://github.com/panjf2000/gnet)都很优秀，感谢你们开源付出。但是目前看你两出的基准测试结果还是有差异的，这样让使用者比较困惑，建议你两能否商量一下拿出一个统一的基准测试。

**Comment by Allenxuxu** [comment]
你把你测试的方法贴出来

**Comment by yale8848** [comment]
https://github.com/panjf2000/gnet_benchmarks  这个是gnet作者出的测试，你可以看看

**Comment by Allenxuxu** [comment]
你可以本地跑跑看，tcpkali 的测试方法是一直发送不管是否接收，测试数据波动比较大。
可以试试 ping pong 测试：https://github.com/Allenxuxu/gev/issues/1

**Comment by Allenxuxu** [comment]
@yale8848  https://blog.csdn.net/Solstice/article/details/5863411 可以看下陈硕的这个文章

 - [测试客户端](https://github.com/Allenxuxu/gev/blob/master/benchmarks/client/main.go)
 - [测试脚本](https://github.com/Allenxuxu/gev/blob/master/benchmarks/bench-pingpong.sh)

**Comment by yale8848** [comment]
好的，谢谢
