### ISSUE TITLE
Server.RunEvery: 参数传递错误

### ISSUE THREAD

**Issue by RussellLuo** [Allenxuxu/gev#9]
当前 [Server.RunEvery](https://github.com/Allenxuxu/gev/blob/39b74a883d9d4f1204292755e4b37f50add516ab/server.go#L85-L87) 的实现：

```go
func (s *Server) RunEvery(d time.Duration, f func()) *timingwheel.Timer {
	return s.timingWheel.ScheduleFunc(&everyScheduler{Interval: time.Second}, f)
}
```

结构体 everyScheduler 中的 Interval 字段应该使用 d 😃

**Comment by Allenxuxu** [comment]
👍 感谢大佬指出！

**Comment by Allenxuxu** [comment]
已经修复了，感谢大佬关注😄

**Comment by RussellLuo** [comment]
相互学习 :smile:
