### ISSUE TITLE
OnMessage 会阻塞 worker 吗？ 

### ISSUE THREAD

**Issue by RaynorGu** [Allenxuxu/gev#94]
如果 OnMessage 需要被阻塞，worker 也会被阻塞吗？稍微测试了下，好像是这样的

**Comment by Allenxuxu** [comment]
> 如果 OnMessage 需要被阻塞，worker 也会被阻塞吗？稍微测试了下，好像是这样的

不太明白你的意思。

OnMessage 里面不能有阻塞操作

**Comment by RaynorGu** [comment]
> > 如果 OnMessage 需要被阻塞，worker 也会被阻塞吗？稍微测试了下，好像是这样的
> 
> 不太明白你的意思。
> 
> OnMessage 里面不能有阻塞操作

如果需要有阻塞操作的话，有什么好的建议吗？

**Comment by Allenxuxu** [comment]
> > > 如果 OnMessage 需要被阻塞，worker 也会被阻塞吗？稍微测试了下，好像是这样的
> > 
> > 
> > 不太明白你的意思。
> > OnMessage 里面不能有阻塞操作
> 
> 如果需要有阻塞操作的话，有什么好的建议吗？

建议 OnMessage  只做消息解析，有非常耗时的操作的话建议 go 出去
