### ISSUE TITLE
关于EventLoop.QueueInLoop的一个疑问

### ISSUE THREAD

**Issue by liyonglion** [Allenxuxu/gev#98]
EventLoop.QueueInLoop的作用是什么？为什么新的connection需要加入到taskQueueW中后调用poll.Wake()，然后再doPendingFunc中回调将新的connection加入到epoll中。为什么不直接将connection直接加入epoll中，原因是什么？谢谢

**Comment by Allenxuxu** [comment]
可以看下这个讨论：https://www.zhihu.com/question/49741301
